//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources.Components.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebNovelDetails_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebNovelDetails_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Web.Resources.Components.Pages.WebNovelDetails_en", typeof(WebNovelDetails_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddChapterButton {
            get {
                return ResourceManager.GetString("AddChapterButton", resourceCulture);
            }
        }
        
        internal static string AddWebNovelTranslationButton {
            get {
                return ResourceManager.GetString("AddWebNovelTranslationButton", resourceCulture);
            }
        }
        
        internal static string ContinueReadingButton {
            get {
                return ResourceManager.GetString("ContinueReadingButton", resourceCulture);
            }
        }
        
        internal static string DisableNotificationsButton {
            get {
                return ResourceManager.GetString("DisableNotificationsButton", resourceCulture);
            }
        }
        
        internal static string EnableNotificationsButton {
            get {
                return ResourceManager.GetString("EnableNotificationsButton", resourceCulture);
            }
        }
        
        internal static string Description_Header {
            get {
                return ResourceManager.GetString("Description_Header", resourceCulture);
            }
        }
        
        internal static string AlternativeNames_Header {
            get {
                return ResourceManager.GetString("AlternativeNames_Header", resourceCulture);
            }
        }
    }
}
