//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources.Views.WebNovel {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddWebNovel_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddWebNovel_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Web.Resources.Views.WebNovel.AddWebNovel_ru", typeof(AddWebNovel_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        internal static string Header_Description {
            get {
                return ResourceManager.GetString("Header_Description", resourceCulture);
            }
        }
        
        internal static string Data_UrlName {
            get {
                return ResourceManager.GetString("Data_UrlName", resourceCulture);
            }
        }
        
        internal static string Data_UrlName_Description {
            get {
                return ResourceManager.GetString("Data_UrlName_Description", resourceCulture);
            }
        }
        
        internal static string Data_OriginalName {
            get {
                return ResourceManager.GetString("Data_OriginalName", resourceCulture);
            }
        }
        
        internal static string Data_OriginalName_Description {
            get {
                return ResourceManager.GetString("Data_OriginalName_Description", resourceCulture);
            }
        }
        
        internal static string Data_Language {
            get {
                return ResourceManager.GetString("Data_Language", resourceCulture);
            }
        }
        
        internal static string Data_Language_Description {
            get {
                return ResourceManager.GetString("Data_Language_Description", resourceCulture);
            }
        }
        
        internal static string Data_Name {
            get {
                return ResourceManager.GetString("Data_Name", resourceCulture);
            }
        }
        
        internal static string Data_Name_Description {
            get {
                return ResourceManager.GetString("Data_Name_Description", resourceCulture);
            }
        }
        
        internal static string Data_Description {
            get {
                return ResourceManager.GetString("Data_Description", resourceCulture);
            }
        }
        
        internal static string Data_Description_Description {
            get {
                return ResourceManager.GetString("Data_Description_Description", resourceCulture);
            }
        }
        
        internal static string Data_Author {
            get {
                return ResourceManager.GetString("Data_Author", resourceCulture);
            }
        }
        
        internal static string Data_Author_Description {
            get {
                return ResourceManager.GetString("Data_Author_Description", resourceCulture);
            }
        }
        
        internal static string Data_IsAdultContent {
            get {
                return ResourceManager.GetString("Data_IsAdultContent", resourceCulture);
            }
        }
        
        internal static string Data_IsAdultContent_Description {
            get {
                return ResourceManager.GetString("Data_IsAdultContent_Description", resourceCulture);
            }
        }
        
        internal static string Data_UsesVolumes {
            get {
                return ResourceManager.GetString("Data_UsesVolumes", resourceCulture);
            }
        }
        
        internal static string Data_UsesVolumes_Description {
            get {
                return ResourceManager.GetString("Data_UsesVolumes_Description", resourceCulture);
            }
        }
        
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
    }
}
